# Generated by Django 3.2.4 on 2021-06-19 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onsitetool', '0002_rename_individuals_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('assessment_location', models.CharField(max_length=50)),
                ('assessment_date', models.DateField()),
                ('change_in_status', models.BooleanField()),
                ('status_overview', models.TextField()),
                ('services_implemented', models.BooleanField()),
                ('services_overivew', models.TextField()),
                ('change_in_plan', models.BooleanField()),
                ('plan_overview', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
