# Generated by Django 3.2.4 on 2021-06-19 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onsitetool', '0003_auto_20210619_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientassessment',
            old_name='services_overivew',
            new_name='services_overview',
        ),
    ]
